### ISSUE TITLE
Add color support in py3status

### ISSUE THREAD

**Issue by lasers** [su8/pinky-bar#1]
Hi. It is already possible to output the data to `py3status` using `external_script` without colors. However, with a little more work, I believe `pinky-bar` can display colors in `py3status` . For this to work, `pinky-bar` should require `--with-py3status` argument to print the program options in different format along with a specialized module `pinky`. 
![](https://raw.githubusercontent.com/su8/pinky-bar/master/img/pic6.png)
Using screenshot as an example, the output should come out like this (minus the `format +=`).
```python
    format = '[\?color=deepskyblue&show CPU]'
    format += ' [\?color=violet&show 0% 0% 0%]'
    format += ' [\?color=yellow&show 41C]'
    format += ' [\?color=deepskyblue&show RAM]'
    format += ' [\?color=violet&show 9%]'
    format += ' [\?color=deepskyblue&show SSD]'
    format += ' [\?color=violet&show 19%]'
    format += ' [\?color=deepskyblue&show Pkgs]'
    format += ' [\?color=violet&show 743]'
    format += ' [\?color=yellow&show Linux 4.4.19-gentoo]'
    format += ' [\?color=deepskyblue&show Voltage]'
    format += ' [\?color=violet&show 1.36 3.34 5.04 12.28]'
    format += ' [\?color=deepskyblue&show Fans/RPM]'
    format += ' [\?color=violet&show 1126 2198]'
    format += ' [\?color=deepskyblue&show Mobo]'
    format += ' [\?color=violet&show ASUSTeK MSA78L-M]'
    format += ' [\?color=yellow&show 39C]'
    format += ' [\?color=deepskyblue&show Volume]'
    format += ' [\?color=violet&show 68%]'
    format += ' [\?color=deepskyblue&show Time]'
    format += ' [\?color=violet&show 09:50 PM]'
```
The `pinky` module then can use the `pinkybar` output as its `format` (with colors this time).

**Comment by lasers** [comment]
Here's the `py3status` module that can output `pinkybar` in colors. [pinkybar.py](https://github.com/lasers/py3status/blob/newmodule-pinkybar/py3status/modules/pinkybar.py)

In the code, I strip `' \n'` off the output. If there's nothing that requires `pinkybar` to print `' \n'` at end, then it could be something to remove. It's a given that this module works okay without colors too.

**Comment by su8** [comment]
I'll look in more details in Thursday. Thanks for the suggestion.

**Comment by su8** [comment]
Hi @lasers, can you test the latest commit and see whether it's working fine ?

With the following configure options `--with-py3status --with-colors`.

Thanks

**Comment by lasers** [comment]
Hi @su8, I tested this. This works perfectly. :+1:

![pinkybar_0](https://user-images.githubusercontent.com/852504/38707071-600d20e8-3e75-11e8-9c69-65f76e7328c0.png)

Py3status can use css color names so you can change the colors to be much closer to your color palette if necessary. This looks really nice. I also made a screenshot using the `format` above. Do what you want with it for your `README`.

![pinkybar_py3status](https://user-images.githubusercontent.com/852504/38707381-c7c4cb86-3e76-11e8-833e-418d44191bcd.png)

Many thanks for adding this support. You may close your first issue. :-)

**Comment by su8** [comment]
Will add even section especially for py3status.

**Comment by su8** [comment]
Just wondering, why the packages are showing 0, did you specified other distro than you currently use to `set.pl` ?

**Comment by su8** [comment]
Thanks for bringing this up to me and commenting down the road.

**Comment by lasers** [comment]
No good reason. I went through the installation and it's printing `1799` okay for me with `Debian`. The last installation was few days ago. I just think I made a mistake somewhere as I was trying many things at once. There should be `--updates` argument too.
