### ISSUE TITLE
CPU percents and hertz

### ISSUE THREAD

**Issue by lasers** [su8/pinky-bar#18]
I caught myself trying `--coreloads` instead of `--coresload`. I think this is not a good name because
I made a mistake. Lol. I suggest this solution to make it more friendly for users.
* Rename `--cpu` to `--cpu-percent`
* Rename `--coresload` to `--cpu-percent-all`
* Make `--cpu-hertz`
* Make `--cpu-hertz-all`

EDIT: Does it make sense to display `--cpu-hertz` (averaged out)? 
EDIT2: `grep MHz /proc/cpuinfo` 
EDIT3: Maybe for `--cpu-hertz*` stuffs, fix `--shell` first and use that instead.

**Comment by su8** [comment]
>Does it make sense to display --cpu-hertz (averaged out)

It shows the maximum cpu clock speed regardless of the used [cpu governor](https://wiki.archlinux.org/index.php/CPU_frequency_scaling#Scaling_governors)

Will rename cpu and coresload.

**Comment by lasers** [comment]
>It shows the maximum cpu clock speed regardless of the used cpu governor

You're right. I tested it with `watch -n0 grep MHz /proc/cpuinfo`. Not worth adding. Thanks for others. :+1:

**Comment by lasers** [comment]
Add `--ram-used`  Used RAM, in MB too. And slightly unrelated, `--title` is broken for me.

**Comment by su8** [comment]
It's called `--ramused`

**Comment by lasers** [comment]
Yes it is. Sorry. I didn't see it with other RAM options, but is there at bottom of the list.

**Comment by lasers** [comment]
When you `-l` (lowercase L), do you get `--ramshared` or `--ramused` in OpenBSD? Both same?

**Comment by su8** [comment]
`--ramused`

https://github.com/su8/pinky-bar/blob/1603b9f41ff8c3e5b26d44cab1119105642841eb/src/openbsd_functions.c#L56

**Comment by lasers** [comment]
Kill `-l` for `--ramused` so we can combine it and put it with other `RAM` options?

**Comment by su8** [comment]
If I "kill" it, the parse will be broken as it expects the key "-l" whenever it's compiled for linux it will be ram shared, otherwise when compiled for OpenBSD it will be ramused.

**Comment by lasers** [comment]
Request to remove `RAM` in all `--ram*` options. Allow `1024/8192` or such. Ty.

**Comment by su8** [comment]
Running out of time, have to go to work. Will do these changes in the weekend or when I have more time, thanks.
