### ISSUE TITLE
Suggestions and Feedback

### ISSUE THREAD

**Issue by lasers** [su8/pinky-bar#2]
Hi again. :blush:  I want to give my suggestions and feedback on `pinkybar`.

`./configure` tells me to install `pciutils`, but it is installed. For Debian, it is `libpci-dev`. Mention this too for Debian/Ubuntu users?

I can't tell which line gave me an error. After omitting many lines, it is `--mobo`. If it could print failed arguments too, then it could be be helpful, partially if users copy and paste things from wiki. Maybe not possible or not important.

Pinkybar came with many arguments. I find that short options are already hard to remember and inadvertently gives us more arguments. Some short options are also confusing, eg `-h` for `--wifiname` or `-g` for `battery`. I think it would be more clean to avoid them altogether and to spell out everything in the config instead. Also easier to parse config without documentation.

Long options sometimes combines letters such as `--swaperc` instead of `--swapperc`.  I question if this is a good idea in the long run and my suggestion is to use something like `--swap-percent`. I also suggest to avoid offering `--kernel` as users can use `--kernel-name --kernel-version` instead.

Using `~/.pinky.conf` might be more obvious than `~/.pinky` and if you need a directory someday, then `~/.pinky` could be it. I also wonder about XDG support, eg `~/.config/pinky/config`.

New argument to make: `--updates` for pending new updates? 

Some arguments could be a bit more explicit such as `--with-weather` to `--with-openweathermap`, similiar to `--with-mpd` in case you want to support more than one weather url.

And another one, `--with[out]-mail` could be renamed to `--with[out]-gmail`. The new `--mail`, I suppose, would be imap w/ server address, port, etc or maybe that's `--imap-mail`. I dunno because users could make their own mail scripts?

See if you can make `--with-mpris` as that one would support more music players than (I think just two) mpd and cmus. mpris works fine with cmus-git and mpd too with a plugin.

`--shell` may be a better name to use than `--notes`. Users can also run `pwgen 20 1` or other commands essentailly removing non-configurable (limited) `--password` and some other commands. Also I can't get this to work with `--notes=$(pwgen 20 1)` as it displays `$(pwgen` for me.

Sorry for the noise!!! :cry:  :drum: :loud_sound:

**Comment by su8** [comment]
>--shell may be a better name to use than --notes. Users can also run pwgen 20 1 or other commands essentailly removing non-configurable (limited) --password and some other commands. Also I can't get this to work with --notes=$(pwgen 20 1) as it displays $(pwgen for me.

Renamed the option to **--shell**, thanks.

![2018-04-13-023833_389x32_scrot](https://user-images.githubusercontent.com/29376083/38711084-d990863c-3ec3-11e8-9ce5-d2ad86de50be.png)

Strange the pwgen command works for me, also the program offers random password generator too.

**Comment by su8** [comment]
Will make the **--password** option to accept argument as number and output random password up to 199 chars.

**Comment by su8** [comment]
>I can't tell which line gave me an error. After omitting many lines, it is --mobo. If it could print failed arguments too, then it could be be helpful, partially if users copy and paste things from wiki. Maybe not possible or not important.

Newer argp versions seems to omit the error messages when using **multiple** options when the program is ran. I just compiled a newer version and it wasn't including the alsa function and it parsed everything up until the volume option. Was wondering why the volume option is not included nor why the error message is not printed and then found out that argp is to blame. When using single options, such as `--mobo` and if it fails, the error message will be printed, but not when it's combined with other options, the program will just carry on.

**Comment by lasers** [comment]
The `pwgen` command works for me in terminal, but not in `~/.pinky`, it seems.

**Comment by lasers** [comment]
Now I'm thinking that `--run` might make more sense (more generic) over `--shell` because of shell, scripts, commands, etc. Also, should I make separate issues or lump them all here to work out the initial kinks? Another issue is that when if I try `pinkybar --ip`, I get `--ip is ambiguous,` with few `--ip*` possibilities... The documentation say it should give me external ip address (ipv4).

**Comment by su8** [comment]
>The pwgen command works for me in terminal, but not in ~/.pinky, it seems.

The parser expects 1 option to be supplied, with or without **=** sign, but by using spaces this increases the supplied options and doesn't work.

>Another issue is that when if I try pinkybar --ip, I get --ip is ambiguous, with few --ip* possibilities...

Did you compiled the program **--with-ip** ?

---

What is the debian command to list all available updates, got the archlinux one.

**Comment by su8** [comment]
Have you tried to extend pinky-bar in any of 13 available languages ? Be aware that python requires `PYTHONPATH` to be set to the directory containing the module.

**Comment by su8** [comment]
Does the `--cpuinfo` option counts your cpu cores correctly, and `--cpuspeed` returns the correct speed in MHz ? Asking because they use assembly and have tested those options on limited number of cpu's.

**Comment by lasers** [comment]
For `ip`... I get `Install curl and or libcurl in order to compile the program`. I already had `curl` and `libcurl3` installed. Debian need `libcurl4-openssl-dev` to make this work. It turns out I need to compile the program `--with-ip`. Works fine now.

`apt list --upgradeable` is new and/or unstable... and can work for you. The old and/or stable is `apt-get upgrade --simulate`. To print number of new packages too (not kept back) is `apt-get dist-upgrade --simulate`.

**Comment by lasers** [comment]
* `--cpuspeed` prints a speed for me, but does not change. I assume it's static.
* `--cpuinfo` gave me `0x (long space) Intel(R)...`. No count and a long space.

**Comment by su8** [comment]
Thanks for the feedback.

**Comment by su8** [comment]
Just added `--ramused`, was trying to balance the available options between the operating systems and made that one exclusive to openbsd.

**Comment by su8** [comment]
The option counts the buffers too, so before you use the command drop the buffers via `sudo sysctl --write vm.drop_caches=3` and it will show the same ammount of memory usage as `free -h` one.

**Comment by lasers** [comment]
Can't `make && make install`.
```
$ make && make install
Making all in src
make[1]: Entering directory '~/src/pinky-bar/src'
make  all-am
make[2]: Entering directory '~/src/pinky-bar/src'
  CXXLD    pinkybar
options.o: In function `parse_opt':
~/src/pinky-bar/src/options.c:356: undefined reference to `get_updates'
~/src/pinky-bar/src/options.c:304: undefined reference to `get_packs'
collect2: error: ld returned 1 exit status
Makefile:497: recipe for target 'pinkybar' failed
make[2]: *** [pinkybar] Error 1
make[2]: Leaving directory '~/src/pinky-bar/src'
Makefile:389: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '~/src/pinky-bar/src'
Makefile:499: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by su8** [comment]
Perform a fresh clone instead `git pull`. Moved the packages into standalone module earlier today.

**Comment by lasers** [comment]
The bullet list is slightly confusing. I wonder if it is better to follow the steps.
>Program Options
>Configure Options
>Installation for...
>Installation for...
>Installation for...

to
>Installation for...
>Installation for...
>Installation for...
>Configure Options
>Program Options

That way, everybody could kinda expect where it ought to be... than to consider where for a second.

**Comment by lasers** [comment]
And to break up `--loadavg` into `--load_1min`, `--load_5min`, `--load_15min` too.

**Comment by su8** [comment]
The loadavg is splitted as you requested, thanks :}

**Comment by lasers** [comment]
Py3status uses `_` for its placeholders so I said `--load_1min` by mistake since it seem that this is one of pinkybar's many arguments often used with `-`... So do you want `--load1_min` or `--load-1min`? I just wanted to point this out.

**Comment by su8** [comment]
`--load-Xmin` seems better alternative.

**Comment by lasers** [comment]
What's the story? Where is @su8? My guess? He got stabbed or a girlfriend. Preferably the latter. Either way, I'm closing this as it is already hard to track where we stand on several issues and you already did great with many things. We don't have to concern ourselves with precisely everything. Thanks.
