### ISSUE TITLE
Remove the hardcoded labels

### ISSUE THREAD

**Issue by lasers** [su8/pinky-bar#25]
>**su** Can you open up another issue to remind me to remove the labels from RAM and drive options ? Thanks in advance.

Hi. Please remove the labels from RAM and drive options. Ideally, it would be good to remove all of the hardcoded labels to offer full / flexible customization but that would break your theme... which is something I do not wish to do. :cry:

**Comment by su8** [comment]
It's brilliant, thanks. If the user wants some label then `--title` can be used to prefix certain option. Will add `--xbm` option for the dzen2 users.

**Comment by lasers** [comment]
See https://github.com/su8/pinky-bar/issues/9#issuecomment-383018481. Thoughts? With this approach, we lose out on `--xbm`, but could replace with `font-awesome-5` + coloring. Anyhow, something to try in a new project... or just disagree. ;-)

**Comment by su8** [comment]
Removed all labels in https://github.com/su8/pinky-bar/commit/8cb1dad8a73462d218dcf86f7657f9d10ad3b327.

**Comment by lasers** [comment]
Untested. I believe you. <3
