### ISSUE TITLE
Require an additional argument --with-colors

### ISSUE THREAD

**Issue by lasers** [su8/pinky-bar#39]
`./configure --prefix=$HOME/.cache --with-py3stauts --with-colors` will produce `dzen2` color instaed of `py3status` color. It didn't take long to find my mistake.

`./configure --prefix=$HOME/.cache --with-colors` (not specified) will also produce `dzen2` color.

I think there should be a `--with-dzen2` color argument and that if we supply `--with-colors` without specifying which one, then it should either print the output without colors or to stop there (error).

Twas a typo.

**Comment by lasers** [comment]
I'm not sure if we would need `--with-colors` anymore.

**Comment by su8** [comment]
with-py3stauts is mistyped that's why it defaults to dzen2. You'll get some warning that there is no such configure option.

**Comment by su8** [comment]
>I think there should be a --with-dzen2 color argument and that if we supply --with-colors without specifying which one, then it should either print the output without colors or to stop there (error)

Will make those changes in the weekend, thanks for the suggestion. ♥

**Comment by lasers** [comment]
New features tested okay. I love it that we have one less favoritism in the code. Thanks! :-)
