### ISSUE TITLE
Icon-Logo design (requested)

### ISSUE THREAD

**Issue by Tobaloidee** [su8/pinky-bar#40]
Hello @su8  

can you tell me what font the text "pinkybar" used?  can I change the fontstyle? for i have come up with something like this that relates with a square-ish motherboard symbol. 

![pinkybar-02](https://user-images.githubusercontent.com/36028424/40280742-963e0a64-5c8a-11e8-9e56-72a2f0beed2d.png)

![pinkybar-01](https://user-images.githubusercontent.com/36028424/40280745-99fded40-5c8a-11e8-88ac-4ec0f63b634a.png)

![pinkybar-03](https://user-images.githubusercontent.com/36028424/40280754-b2a7659c-5c8a-11e8-9b2e-465f54647140.png)

will wait for your feedback

**Comment by su8** [comment]
Yes that's what I want, looks great.

**Comment by su8** [comment]
Can you open up a pull request (PR) and add the top image ![](https://user-images.githubusercontent.com/36028424/40280754-b2a7659c-5c8a-11e8-9b2e-465f54647140.png) P followed by pinkybar

**Comment by Tobaloidee** [comment]
created PR #41 @su8  

I am so glad to have helped and contributed to your great project! :)

**Comment by Tobaloidee** [comment]
Hello @su8 , you can download the other versions of your logo here on the link below. Thanks again!

https://drive.google.com/drive/u/0/folders/1cglgt-MrYqohSRbgaINANWj1myRhkY2u

Best regards!

**Comment by su8** [comment]
Thank you sir ♥
