### ISSUE TITLE
Remove extra whitespace in DVD

### ISSUE THREAD

**Issue by lasers** [su8/pinky-bar#5]
`with-dvd` and `--dvdstr`. `The vendor and model name of your cdrom/dvdrom`.

Got: 
```python
vendor: 'hp        '
model: 'DVD A   DH16ACSHR'
>hp        DVD A   DH16ACSHR
```
Expected:
```python
vendor: 'hp'
model: 'DVD A DH16ACSHR'
>hp DVD A DH16ACSHR
```

`HP` would look better though. Also, cool useless option.  (ツ)

EDIT: Maybe just uppercase the vendor? `HP`, `DELL`, etc.

**Comment by su8** [comment]
It's either the one detected from the kernel or lcdio, aka **--with-dvd**,

To see the one comming from the kernel `cat /sys/class/block/sr0/device/vendor` and `cat /sys/class/block/sr0/device/model`

To see whether it's comming from lcdio: `gcc -Wall -Wextra -lcdio -O2 dvd.c -o out; ./out`

save it as **dvd.c**

```c
#include <stdio.h>
#include <stdlib.h>
#include <cdio/cdio.h>
#include <cdio/mmc.h>
int main(void) {
  CdIo_t *p_cdio = cdio_open(NULL, DRIVER_DEVICE);
  cdio_hwinfo_t hwinfo;
  if (NULL == p_cdio) {
    return -1;
  }
  if (mmc_get_hwinfo(p_cdio, &hwinfo)) {
    printf("%s %s\n", hwinfo.psz_vendor, hwinfo.psz_model);
  }
  if (NULL != p_cdio) {
    cdio_destroy(p_cdio);
  }
  return 0;
}
```

**Comment by lasers** [comment]
```bash
$ cat /sys/class/block/sr0/device/vendor | cat -E
hp      $
$ cat /sys/class/block/sr0/device/model | cat -E
DVD A  DH16ACSHR$
$ gcc -Wall -Wextra -lcdio -O2 dvd.c -o out; ./out
hp       DVD A  DH16ACSHR$
```

**Comment by su8** [comment]
It should be fixed for the vendor one in the latest commit, thanks for reporting this one.

**Comment by lasers** [comment]
Tested. Fixed. `vendor` only. Ty.
