### ISSUE TITLE
Weather breaks output data for py3status

### ISSUE THREAD

**Issue by lasers** [su8/pinky-bar#6]
Got: 
```python
'Out [\?color=yellow&show Fog 4C Wind 1 m/s'
```
Expected: 
```python
'Out [\?color=yellow&show Fog 4C Wind 1 m/s]'
```

Also, the bar `|` should be escaped with a slash, `\|`, in `py3status`. Not the issue here.

**Comment by su8** [comment]
Forgot this one as it's not using the format specifiers defined in options_constants.h. Thank you.

**Comment by lasers** [comment]
Tested. Fixed.
