### ISSUE TITLE
Extending pinkybar with scripts and other arguments

### ISSUE THREAD

**Issue by lasers** [su8/pinky-bar#8]
Hi. I tried this.

```bash
./configure --prefix=$HOME/.cache --with-py3status --with-colors --with-python2
make && make install
```
```
PYTHONPATH=~/test ~/.cache/bin/pinkybar --python test.py
```
```python
#!/usr/bin/env python2
from __future__ import print_function
from os import getloadavg
print(', '.join([format(x) for x in getloadavg()]), end='')
```
Result...
```
0.04, 0.09, 0.12[\?color=yellow&show 0]
```

I can add `[\?color=blue&show {result}]` myself for `py3status`, but I do not know how to do that for other things like `dwm`, `xmobar`, `awesomewm`, `tmux`, `ncurses`, etc as they require different formatting which I am not familiar with.

If users write scripts and then they might wanted things to be formatted accordingly to the arguments they gave... partially with colors too. I have other issue of acknowledging that most strings, colors, etc are hardcoded and that there is not lot of flexible in customizing `~/.pinky` like a bash shell.

I said no to `--load-xmin` because we now have `Load/avg 1 Load/avg 5 Load/avg 15`. Users can want either `LoadAvg 1` (Problem solved by splitting up) or `LoadAvg: 1, 5, 15` (Problem created by splitting up).... and possibly more.

Sorry for unleashing issues. I can... stop.

**Comment by su8** [comment]
You are missing the function `uzer_func` that has to return single string, not other type.

**Comment by su8** [comment]
```python
from __future__ import print_function
from os import getloadavg
def uzer_func():
    a=', '.join([format(x) for x in getloadavg()])
    return a
```

**Comment by su8** [comment]
>I said no to --load-xmin because we now have Load/avg 1 Load/avg 5 Load/avg 15. Users can want either LoadAvg 1 (Problem solved by splitting up) or LoadAvg: 1, 5, 15 (Problem created by splitting up).... and possibly more.

Will add another option to stand as "header" or title that can be used to prefix certain option with custom title.

**Comment by lasers** [comment]
I added the missing `uzer_func`, then you pasted code. Both gave me nothing. It's also printing `[\?color=yellow&show 0]` which I think came from nowhere.

With just `--time` in `~/.pinky`, it printed the time okay, but if I tried `PYTHONPATH=~/src/pinky-python ~/.cache/bin/pinkybar --python example.py`, I get `[\?color=yellow&show 0]`. Also, does this mean I need to customize `pinkybar` module to include `PYTHON... line`?

**Comment by su8** [comment]
Can you test `PYTHONPATH=~/test ~/.cache/bin/pinkybar --python test` notice that test doesn't include test.py

**Comment by lasers** [comment]
>Will add another option to stand as "header" or title that can be used to prefix certain option with custom title.

Yes. I wanted to make an issue about that, but felt that it would be too much because that mean removing all existing headers as well as symbols, characters, etc.. I also was wondering about `--color`.... so... Lot of things... hence me not making a post.  Will check.

**Comment by lasers** [comment]
Okay. This works fine now with `example`. Don't use `example.py`. Ty. :+1:

**Comment by lasers** [comment]
I will be brave and make a post about that issue. Ty again.

**Comment by su8** [comment]
Added the custom title and removed the `Load/avg` label from the three `load-xmin` functions.

**Comment by lasers** [comment]
Can't `make` with py3status, colors, python3
```
$ make
Making all in src
make[1]: Entering directory '~/src/pinky-bar/src'
make  all-am
make[2]: Entering directory '~/src/pinky-bar/src'
  CXXLD    pinkybar
Makefile:506: recipe for target 'pinkybar' failed
make[2]: Leaving directory '~/src/pinky-bar/src'
Makefile:398: recipe for target 'all' failed
make[1]: Leaving directory '~/src/pinky-bar/src'
Makefile:502: recipe for target 'all-recursive' failed
```

**Comment by su8** [comment]
Your default python is python2, and the program (extend.m4) is looking for python-config. Will see what I can do to detect the correct python2.7-config or python3.6-config and not python-config.

**Comment by su8** [comment]
On my system my default python version is 3.6 and tried a lot of changes to extend.m4 but it just doesn't want `--with-python2`, still searches for python3.X no matter what I specified or comment in the python3 code in there.

**Comment by lasers** [comment]
How do I use both `PYTHONPATH=~/scripts ~/.cache/bin/pinkybar --python getloadavg` and `--time` in `~/.pinky`?

**Comment by su8** [comment]
Execute bare `PYTHONPATH=~/scripts ~/.cache/bin/pinkybar` and in your config type `--python=getloadavg` with **=** sign.

**Comment by su8** [comment]
Can you try to import py3status and operate it from `uzer_func` ?

**Comment by lasers** [comment]
I'm trying to run `--python getloadavg` on `pinkybar` module right now No problem running this on the terminal.

**Comment by lasers** [comment]
I came up with something. Users need to specify `path` in the config. (https://github.com/lasers/py3status/blob/newmodule-pinkybar/py3status/modules/pinkybar.py)

**Comment by su8** [comment]
Open up a PR.

**Comment by su8** [comment]
It works fine on my system with python3, wondering where it fails.

**Comment by su8** [comment]
Can you run `gdb` as it's compiled with -g flag and post what it shows ?

**Comment by lasers** [comment]
Dunno. Went to Py2. You say this. I come back to Py3. Working okay. Cheers. :clinking_glasses:

**Comment by su8** [comment]
Just to confirm that python2 and python3 are working fine - https://streamable.com/sw4ey

**Comment by lasers** [comment]
You want this? https://github.com/lasers/pinky-bar/commit/d7147d6e3d17f58fb426dd7ef6cfba886a995c12

Lot of minor touchups, spelling typos, capitalization, removing beginning `The`, not insulting linux brands (eg, VoidLinux --> Void Linux) and few more. Also, `solusos` should be `solus` too, but I hadn't looked where you put that in (for set.pl thing). It's lot of tiny tiny tweaks.

**Comment by su8** [comment]
Yes I really want those changes. Open up a PR.

**Comment by lasers** [comment]
Okay. I'll do that when I'm 100% finished with nitpicking.

**Comment by lasers** [comment]
Question? Hmm. Can you explain more about...
* `--dwm` What does this does/query?
* `--sensors`... Alternative to what?

Sorry. Your `README.md` alone is almost 1K. It's taking longer than I thought.

**Comment by su8** [comment]
`--with-dwm` outputs the data to the root window which dwm is using to parse and show it to the user in the form of statusbar.

`--sensors` is alternative way to obtain data instead using the pre-defined paths that the kernel is using to store data such as the one provided for motherboard vendor/model and cpu temperature.

**Comment by lasers** [comment]
Just pushed. https://github.com/lasers/pinky-bar/blob/readme/README.md. Feel free to preserve anything. I'm done with `Compile Options`. Kinda looking at `Program Options` now.

**Comment by lasers** [comment]
Thoughts?

**Comment by su8** [comment]
It looks great :+1: , waiting for PR.

**Comment by lasers** [comment]
Question: If users extend `pinkybar` with scripts, how can we pass the arguments to script? I can hardcode it inside the script, but this is more for `pinkybar` than for the `user`. I was thinking about something like this...

`pinkybar --python nvidia_smi=temperature.gpu,memory.used` --> Prints `39C, 224MB`

If you have NVIDIA GPU, you can try `nvidia_smi` w/ `py3status`. The variable names also comes from NVIDIA's `nvidia_smi` command.

>$ nvidia-smi --format=csv,noheader,nounits --query-gpu=temperature.gpu,memory.used
63, 192

**Comment by su8** [comment]
>Question: If users extend pinkybar with scripts, how can we pass the arguments to script?

You can't pass arguments as the "scripts" get imported as modules.

**Comment by su8** [comment]
What you can try is write another module and import it on-the-fly.

**Comment by lasers** [comment]
I realize it would be better to use `--shell` in the config.
```
--shell=nvidia_smi --format=csv,noheader --query-gpu=temperature.gpu,nounits --space --title C
--shell=nvidia_smi --format=csv,noheader --query-gpu=memory.used
```
Notice the absent `nounits` in second line as it would print `192 MiB`.
Would come out as `63 C 192 MiB` (in same color).

Also, `--text  C` (extra space) results in `option --title requires an argument.` No space in `--text` either. Hmm, tough. Anyhow, having `--shell` work in the config is a must-have feature. \o/

**Comment by su8** [comment]
Got it to work with --shell in the config, replace the following code in **options.c**:

```c
void
parse_konf(char *combined) {
  FILE *fp = NULL, *fp2 = NULL;
  char *ptr = NULL;
  char *ello[] = { (char *)PACKAGE_STRING, NULL };
  char buf[100], conf[50], temp[100], temp2[VLA], temp3[VLA];
  const char *const home = getenv("HOME") ? getenv("HOME") : "empty";
  struct arguments arguments = {
    .all = combined
  };

  snprintf(conf, 49, "%s%s", home, "/.pinky");
  if (NULL == (fp = fopen(conf, "r"))) {
    exit_with_err(ERR, "~/.pinky doesn't exist or $HOME is unset");
  }

  while (NULL != (fgets(buf, 99, fp))) {
    if (EOF == (sscanf(buf, "%[^\n]", temp))) {
      CLOSE_FP(fp);
      exit_with_err(ERR, "empty line(s) detected.");
    }
    ptr = temp;
    while (0 != (isspace((unsigned char) *ptr))) {
      ptr++;
    }
    if ('-' == *ptr && '-' == *(ptr+1)) {
      if ('s' == *(ptr+2) && 'e' == *(ptr+4)) {
        if (EOF == (sscanf(ptr, "%*s %[^\n]", temp2))) {
          CLOSE_FP(fp);
          exit_with_err(ERR, "empty line(s) detected - EOF.");
        }
        if (NULL == (fp2 = popen(temp2, "r"))) {
          continue;
        }
        CHECK_FSCANF(fp2, "%[^\n]", temp3);
        GLUE(combined, "%s ", temp3);
        if (-1 == (pclose(fp2))) {
          exit_with_err(CANNOT_CLOSE, "popen()");
        }
        continue;
      }
    }
    ello[1] = ptr;
    argp_parse(&arg_parser, 2, ello, ARGP_IN_ORDER, NULL, &arguments);
  }
  CLOSE_FP(fp);
}
```

**Comment by lasers** [comment]
```
sh: 1: Field: not found
pinkybar 1.00.00: Error: fscanf() failed
```
with...
```
--time
--updates
--cpu-percent
--cpu-percent-all
--cpuspeed
--packages
--cputemp
--shell $(nvidia-smi --format=csv,noheader --query-gpu=temperature.gpu,nounits)
--shell $(nvidia-smi --format=csv,noheader --query-gpu=memory.used)
```

**Comment by su8** [comment]
Copy and paste the code as I edited it

```

--shell nvidia-smi --format=csv,noheader --query-gpu=temperature.gpu,nounits
--shell nvidia-smi --format=csv,noheader --query-gpu=memory.used
```

**Comment by lasers** [comment]
@su8 Do you notice that it ignore other arguments in the config?

**Comment by su8** [comment]
That's why I told you to copy it again, pushed the newer changes to the repository. Perform `git pull`.
